from flask import Flask

app = Flask(__name__)

#If y'all wanna test this refer to the README, you'll need to set up some stuff
@app.route('/')
def index():
    return "Hello world"

if __name__ == '__main__':
    #cert and key generated by mkcert
    app.run(ssl_context=('localhost.pem', 'localhost-key.pem'))
